apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fans-cluster
  region: ap-northeast-2
  version: "1.31"

# VPC 설정
vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

# IAM 설정
iam:
  withOIDC: true

# Node Groups
managedNodeGroups:
  - name: fans-nodegroup
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 30
    volumeType: gp3
    labels:
      role: worker
    tags:
      nodegroup-name: fans-nodegroup
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true

# CloudWatch 로깅
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
