# ========================================
# Frontend Deployment (React)
# 포트: 3001
# ========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fans
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 907123164281.dkr.ecr.ap-northeast-2.amazonaws.com/fans-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http

        # 환경 변수
        env:
        - name: PORT
          value: "3001"
        - name: REACT_APP_API_URL
          value: "https://api.fans.ai.kr"
        - name: REACT_APP_AI_SERVICE_URL
          value: "https://ai.fans.ai.kr"

        # 리소스 제한
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Health Check
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fans
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  selector:
    app: frontend

---
# HPA for Frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: fans
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
