# FANS Summarize AI Service
# Python FastAPI + Gemini API (Port 8000)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarize-ai
  namespace: fans
  labels:
    app: summarize-ai
    tier: ai
    project: FANS
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summarize-ai
  template:
    metadata:
      labels:
        app: summarize-ai
        tier: ai
    spec:
      containers:
      - name: summarize-ai
        image: 907123164281.dkr.ecr.ap-northeast-2.amazonaws.com/dw-fans/summarize-ai:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP

        # 환경변수
        env:
        - name: PORT
          value: "8000"
        - name: PYTHON_ENV
          value: "production"

        # 리소스 제한 (AI 서비스는 CPU/Memory 많이 사용)
        resources:
          requests:
            cpu: 200m
            memory: 2Gi
          limits:
            cpu: 1500m
            memory: 5Gi

        # Health Check (모델 로딩 시간 고려)
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: summarize-ai
  namespace: fans
  labels:
    app: summarize-ai
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: summarize-ai

---
# HPA - AI 서비스는 트래픽에 따라 스케일링
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: summarize-ai-hpa
  namespace: fans
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: summarize-ai
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
