apiVersion: v1
kind: ConfigMap
metadata:
  name: fans-config
  namespace: fans
data:
  # API 설정
  API_PORT: "3000"
  NODE_ENV: "production"

  # AI 서비스 URL (내부 서비스 DNS)
  SUMMARIZE_AI_URL: "http://summarize-ai-service:8000"
  BIAS_ANALYSIS_AI_URL: "http://bias-analysis-ai-service:8002"

  # Classification API
  CLASSIFICATION_API_URL: "http://classification-api-service:5000"
  CLASSIFICATION_API_PORT: "5000"

  # Crawler 설정
  CRAWLER_SCHEDULE: "*/30 * * * * *"  # 30초마다

  # Scheduler 설정
  SCHEDULE_INTERVAL: "*/10 * * * *"  # 10분마다
  RUN_ON_START: "false"
  SUMMARY_BATCH_SIZE: "50"
  KEYWORD_BATCH_SIZE: "50"
  BIAS_BATCH_SIZE: "50"

  # 카카오 OAuth
  KAKAO_REDIRECT_URI: "https://api.fans.ai.kr/api/auth/kakao/callback"

  # JWT
  JWT_EXPIRES_IN: "7d"
